module.exports = {
    ROLE_ADMIN: 'ADMIN',
    ROLE_GUEST: 'GUEST'
  }

  module.exports = {
    TYPE_VERB: 'VERBO',
    TYPE_ADVERB: 'ADVERBIO',
    TYPE_ADJECTIVE: 'ADJETIVO',
    TYPE_OBJECT: 'SUSTANTIVO',
    TYPE_IDIOM: 'EXPRESIÓN, PERÍFRASIS',
    TYPE_INTERJECTION: 'INTERJECCIONES',
  }

  module.exports = {
    STYLE_GENERAL: 'GENERAL',
    STYLE_FORMAL: 'FORMAL',
    STYLE_COLLOQUIAL: 'COLLOQUIAL',
    STYLE_VULGAR: 'VULGAR',
    STYLE_INSULT: 'INSULT',
  }

  module.exports = {
    SCOPE_LOCAL: 'LOCAL',
    SCOPE_REGIONAL: 'REGIONAL',
    SCOPE_NATIONAL: 'NATIONAL',
    SCOPE_WORLDWIDE: 'Worldwide',
    SCOPE_OTHER: 'OTHER',
    
  }

